source 'https://rubygems.org'


gem 'rails', '4.2.6'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

# To allow for Cross-Origin Resource Sharing
gem 'rack-cors'

# For generation of fake records
gem 'faker'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
	gem "rspec-rails"
	gem "shoulda-matchers"
end

group :development, :test do
	gem "factory_girl_rails"
	gem 'ffaker'
end

group :production do
	gem 'rails_12factor'
end

group :development do
	gem 'pry-rails'
	gem 'byebug'
end

gem 'active_model_serializers'

gem "devise"
